name: libdivecomputer_example
description: Demonstrates how to use the libdivecomputer plugin.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  libdivecomputer:
    path: ../
  
  flutter_blue_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
