include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules beyond flutter_lints
    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - require_trailing_commas
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    
    # Treat missing return values as errors
    missing_return: error
