name: libdivecomputer
description: A Flutter plugin for libdivecomputer, enabling communication with dive computers via Bluetooth.
version: 0.1.0
homepage: https://github.com/yourusername/libdivecomputer

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.0.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LibdivecomputerPlugin
      macos:
        pluginClass: LibdivecomputerPlugin
